### ISSUE TITLE
Remove generation in favour of 'pull from repo'

### ISSUE THREAD

**Issue by mcdonnelldean** [apparatus/fuge#100]
Overall there seems to be consensus that the generator portion of fuge is doing too much. However there is a use case in being able to spin up repos quickly. With that in mind the idea would be to,

- remove the generation portion of fuge
- replace with the ability to pull a repo via github
- deprecate any of the associated generation modules 

@apparatus/contributors Any opinions on how this should function. I would personally like to be able to do something like,

```
fuge generate --url mcdonnelldean/some-repo
```

The basic idea being I can set templates as links to a given repo. I'm not too gone on the names I used but that's the intent.

- _updated to matteo's suggested implementation_

**Comment by mcollina** [comment]
IMHO let's support:

`fuge generate --url mcdonnelldean/some-repo`

the other bit is sugar on top.

**Comment by lucamaraschi** [comment]
I agree with @mcollina

**Comment by mcdonnelldean** [comment]
@mcollina @lucamaraschi I'm all for the easier option :D My feeling is we can add storage functionality via the extension system planned later. Are well all agreed it just pulls a template as is, no trying to generate it or run it through yo or anything.

**Comment by mcdonnelldean** [comment]
@mcollina @lucamaraschi Any thoughts on a better name than generate? Generate seems wrong in the context above. @mihaidma is going to take a crack at this. Maybe `fuge pull` or `fuge get`?

**Comment by mcollina** [comment]
I would keep generate, it remembers rails generator. Marketing wise, it
might be better.
I also think fuge get is nice as well.
Il giorno mar 12 lug 2016 alle 16:35 Dean McDonnell <
notifications@github.com> ha scritto:

**Comment by mcdonnelldean** [comment]
@mcollina Good point, I'd probably like to reuse generate to do something else though. @mihaidma For now use generate and lets figure it out once the implementation is done.

**Comment by mihaidma** [comment]
there is already a `fuge pull` that does a git pull against all services: https://github.com/apparatus/fuge/blob/master/fuge.js#L120

should I extend it with `fuge pull git_repo` to implement the functionality above?

**Comment by mcdonnelldean** [comment]
Oh! That's interesting. So fuge pull is pulling in anything named in the system. I think this is a good way to add this functionality. @mcollina @lucamaraschi Any comments?

**Comment by mihaidma** [comment]
Regarding the post below: git pull actually has the form `fuge pull <compose-file>` (adding one more parameter might not be the best idea). Implemented a `fuge generate <Github repo>` for the moment as it seems better to me.

As of functionality implemented the following flow:
- The user calls `fuge generate <Github repo>`. The Github can be any valid Github format like __user/repo__ or __https or ssh__ format,
- The github data is parsed and a __https__ repo url is generated like `https://github.host/github.repo.git`,
- The repo is cloned locally.

I could add the following enhancements:
- If full Github url is inserted then the clone is made as the user specified in the full url (https or ssh),
- I could add in config the possibility to set a default for cloning (https or ssh)

I would implement the first option as it seems useful to me.

What do you think?

**Comment by mcdonnelldean** [comment]
Yeah that seems all good. I'd add the first enhancement. Lets forget the second one for now.
