### ISSUE TITLE
Not working on native Docker 1.12 (native) on Mac os X

### ISSUE THREAD

**Issue by mcollina** [apparatus/fuge#110]
Something is wrong in resolving the ports I think.

Even when setting `proxy: 'none'`, I get:

[frontend - 87964]: 2016-07-08T11:40:37.842Z mqqaw2uk1ehs/1467978009236/87964/- ERROR   act     client$         OUT             cmd:read,role:serialize 7       {role:serialize,cmd:read,sensorId:1,start:2016-07-08T11:30:37+00:00,end:2016-07-08T11:40:37+00:00}   ENTRY   (69f7b) -       seneca: Action cmd:read,role:serialize callback threw: Cannot read property '0' of null.     act_callback    {message:Cannot read property '0' of null,pattern:cmd:read,role:serialize,instance:Seneca/1.1.0/mqqaw2uk1ehs/14 TypeError: Cannot read property '0' of null
[frontend - 87964]:     at Seneca.<anonymous> (/Users/matteo/Repositories/micro-services-tutorial-iot/step4/frontend/api/index.js:19:16)
[frontend - 87964]:     at act_done (/Users/matteo/Repositories/micro-services-tutorial-iot/node_modules/seneca/seneca.js:1231:21)
[frontend - 87964]:     at Seneca.<anonymous> (/Users/matteo/Repositories/micro-services-tutorial-iot/node_modules/seneca/node_modules/gate-executor/gate-executor.js:155:20)
[frontend - 87964]:     at Object.wrapper [as done] (/Users/matteo/Repositories/micro-services-tutorial-iot/node_modules/seneca/node_modules/seneca-transport/node_modules/lodash/index.js:3095:19)
[frontend - 87964]:     at internals.Utils.callmeta (/Users/matteo/Repositories/micro-services-tutorial-iot/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:110:22)
[frontend - 87964]:     at internals.Utils.handle_response (/Users/matteo/Repositories/micro-services-tutorial-iot/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:95:8)
[frontend - 87964]:     at /Users/matteo/Repositories/micro-services-tutorial-iot/node_modules/seneca/node_modules/seneca-transport/lib/http.js:129:25
[frontend - 87964]:     at /Users/matteo/Repositories/micro-services-tutorial-iot/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:472:20
[frontend - 87964]:     at finish (/Users/matteo/Repositories/micro-services-tutorial-iot/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/lib/index.js:326:16)
[frontend - 87964]:     at wrapped (/Users/matteo/Repositories/micro-services-tutorial-iot/node_modules/seneca/node_modules/seneca-transport/node_modules/wreck/node_modules/hoek/lib/index.js:866:20)

In https://github.com/nearform/micro-services-tutorial-iot (step 4)

**Comment by mihaidma** [comment]
@mcollina 
It reproduces also on Fedora 23 if i start all services with `start all`.
But if I start services one by one it works...

**Comment by mcdonnelldean** [comment]
I tested this and also step 8 which is the fully working one. It works fine. You need to run influx first because influx but after that it should work fine. The problem most likely lays in the step, not fuge.
