### ISSUE TITLE
Add support for TypeScript [enhancement]

### ISSUE THREAD

**Issue by CelsoSantos** [apparatus/fuge#120]
I'd love to have the ability to generate services in TypeScript rather than just JS.

Any chance we could have a --typescript/-ts option which would generate the services (and maybe also pull the TypeScript definition for Seneca into the project)?

It would also be very nice to run `tsc` (for building JS from TS) per service/folder before running `npm install`

**Comment by mcdonnelldean** [comment]
@CelsoSantos In the end we took the generation out in favour of a simple cloning tool. We felt there was too much in supporting the generator system as is.

We are hoping to make some changes soon however that will involve pluggability so experiences like you describe can be plugged in for a tailored fit.

CC @lucamaraschi 

I'm going to close for now as this is all still in planning and the generator is gone but we'll make a note of this for sure.
