### ISSUE TITLE
Support for docker-compose v2 keys

### ISSUE THREAD

**Issue by dimashirokov** [apparatus/fuge#121]
Can I use the keys like _services, volumes, networks_ in the docker-compose file?
When I try to start fuge, receive an warning:
**running**: version
**warning**: version not started, missing execute statement
...
**running**: __proxy

**Comment by mcdonnelldean** [comment]
@dimashirokov Right now only v1 is supported. Please see changes to the readme for turning on and off the proxy. V2 is much more complex than V1 so it will take time to do. 

Merged with #128
