### ISSUE TITLE
Update doc for fuge generate

### ISSUE THREAD

**Issue by mihaidma** [apparatus/fuge#124]
Update the fuge generate doc with a few samples of github supported formats.

**Comment by davidmarkclements** [comment]
you'll also need to update the gif

**Comment by mihaidma** [comment]
As there are over 40 combinations of valid github url formats added in docs only a sample for the main usage case: https://github.com/apparatus/fuge/pull/131
The readme is updated and contains no gif.

Will close this as there is another issue that will define the specs of how to build the help for it: https://github.com/apparatus/fuge/issues/126
