### ISSUE TITLE
fuge generate help

### ISSUE THREAD

**Issue by davidmarkclements** [apparatus/fuge#126]
I'd like to see `fuge generate help` which should list the "official repos" which can be pulled from, also - we need an official repo list

**Comment by davidmarkclements** [comment]
also .. other than this (offical repo list)  how is fuge generate superior to git clone? 

also .. what if `fuge generate` with no args cloned a "primary" official repo

**Comment by davidmarkclements** [comment]
also .. do we have any repos atm?

**Comment by mcdonnelldean** [comment]
For now fuge generate is gone (aliased to clone) and clone is just a simple pull to make things convenient. This frees Generate up to be a proper (working) solution again.
