### ISSUE TITLE
fuge & docker-compose

### ISSUE THREAD

**Issue by tomdavidson** [apparatus/fuge#137]
Mind elaborating on what fudge gives us over docker-compose? 
1. I see that I can just node rather than docker which is significant.
2. Interactive shell  is nice, but I can use docker ps and tail ect ....

This is not dogging fuge, just a newb getting up to speed.

**Comment by thekemkid** [comment]
Its much faster not running docker builds all the time for node services, and the auto restarts within fuge are awesome.

The shell gives you access to additional dev tooling such as the debug and profile commands. This is quite powerful when developing & hunting bugs, to just pick one of your services, turn it off and restart it in debug or profiling mode.

In the end, if developing with a few node.js services, I like using this as a quick service runner/tool.

**Comment by thekemkid** [comment]
On the case of deployment, I'm not really able to comment on fuge's deployment capabilities, as I have only ever wanted to use it for dev. Deployment is a separate beast completely - I don't deploy with docker-compose, I have services deployed in a kubernetes cluster with the config that entails. Another fancy tool for the same job, eh? 😆

I'm sure others can chime into this converation and correct me where I'm wrong, I haven't dived in much deeper than the shell commands listed in the readme 😄

**Comment by tomdavidson** [comment]
Thanks for the discussion. It is definitely helpful. I think I will try to use some of fuge in Docker Compose so that I can control other services such as Redis all together.

**Comment by pelger** [comment]
Hey @tomdavidson - yes fuge is 100% a development tool. The aim is to provide a rapid development shell for microservices. Yes you can use docker compose to do this as well but we wanted a tool that was oriented to development only particularly as we will be expanding on some of the other aspects of fuge over the coming months  - for example template service generation.
