### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by vforv** [apparatus/fuge#162]
Is possible to use typescript with fuge?
How can I set up to run ts-node instead node?

**Comment by pelger** [comment]
Type script isn't supported directly but should run as type process. It should be fairly simple to add. Ping me back on this thread if you're interested / have the time and I can guide you on creating a PR for this!

**Comment by vforv** [comment]
I found way... Just added ts-node to run proccess

**Comment by pelger** [comment]
Excellent! I'll close this issue - Thanks!
