### ISSUE TITLE
sending SIGKILL to  child process: (reload services not working)

### ISSUE THREAD

**Issue by vforv** [apparatus/fuge#163]
Getting error when run last beta version of fuge:

$start all

sending SIGKILL to  child process: 3755
sending SIGKILL to  parent process: 3745
sending SIGKILL to  child process: 3755
sending SIGKILL to  parent process: 3745
[apigateway] exit - status: normally duration: 1s
[apigateway] restarting
[apigateway] file change: esparse
[apigateway] file change: esvalidate
sending SIGKILL to  child process: 3755
sending SIGKILL to  parent process: 3745
sending SIGKILL to  child process: 3755
sending SIGKILL to  parent process: 3745
sending SIGKILL to  child process: 3755
sending SIGKILL to  parent process: 3745
sending SIGKILL to  parent process: 3745
sending SIGKILL to  parent process: 3745

After that server reload not working on file change.

fuge: 2.0.2
fuge-runner: 2.0.1
fuge-config: 2.0.1
fuge-dns: 2.0.0

**Comment by pelger** [comment]
Thanks for the report, could you please attach your fuge configuration to this issue.

**Comment by vforv** [comment]
It was problem with config params. I added it directly in fuge yml file and it works now.

**Comment by pelger** [comment]
Excellent! will close this issue - thanks!
