### ISSUE TITLE
no test script specified

### ISSUE THREAD

**Issue by vforv** [apparatus/fuge#165]
I got this result when I run fuge test...
```
skipping [bases] - no test script specified
skipping [apigateway] - no test script specified
skipping [ping] - no test script specified
skipping [repl] - no test script specified
skipping [seed] - no test script specified
skipping [user] - no test script specified

```

I have test script in package.json... like this:

`"test": "lab -a code -t 100 -L -v -T ./node_modules/lab-transform-typescript",`

Why it not run?

**Comment by pelger** [comment]
Fuge runs its tests from the fuge config file (usually fuge.yml) to link it to your package.json tests add `test: npm test` to have fuge run your npm tests. Hope that helps - let me know on this thread if you still have problems and I'll send a more detailed example - Thanks!
