### ISSUE TITLE
Is this still maintained? 

### ISSUE THREAD

**Issue by danielo515** [apparatus/fuge#174]
Hello,
Sorry for the ping and my scepticism, but is this project still maintained?
Most recent commit is almost one year ago and documentation seems to be at barebones, half cooked. 
I'm using it at work and I'm very pleased, but I'm worried about long term support. 

Regards

**Comment by danielo515** [comment]
Sure I am, this has the potential to save me hours of work and tooling. Just let me know how

**Comment by pelger** [comment]
Cool - getting a work plan organized this end will give you a shout back early next week!
