### ISSUE TITLE
Is there any way to pull passwords / secrets?

### ISSUE THREAD

**Issue by marcpaskell** [apparatus/fuge#178]
Hi - thanks for fuge guys... really helped us out over the last few months/years!

Is there a way to include passwords / secrets from another file / location - k8 stylie? 

I'd like to share my fuge config with others in the team but obviously don't want usernames / passwords going into git.

Cheers

**Comment by pelger** [comment]
Glad it's useful! Currently fuge supports inclusion of a docker compose file: 

https://github.com/apparatus/fuge-examples/blob/master/using-docker-compose/fuge/fuge.yml

Which might be of use? Otherwise can you detail exactly how you'd like this to work and we can take a look.
