### ISSUE TITLE
"quit" should also exit

### ISSUE THREAD

**Issue by rjrodger** [apparatus/fuge#19]

**Comment by AdrianRossouw** [comment]
hey @rjrodger, i'm not sure I have the context right to understand what this means...

do you mean that if you quit the fuge shell, it doesn't exit the services?

**Comment by rjrodger** [comment]
you can type exit to quit, but you can't type quit to exit

**Comment by matthewoconnor-development** [comment]
@rjrodger I had this implemented in my current pull request but was told that two way is not necessary. Happy to make the change again though.

**Comment by mcollina** [comment]
That was me. I think having two ways for exiting is confusing.

`exit` is the standard for exiting terminals, you can type that in bash and it will exit the prompt. You can't type quit.

**Comment by AdrianRossouw** [comment]
i think having an alias for certain commands is fine. we would only document exit.

**Comment by pelger** [comment]
quit and exit already :)

**Comment by AdrianRossouw** [comment]
i'm on this.

ctrl-d should also exit.

**Comment by rjrodger** [comment]
+1 user experience win
