### ISSUE TITLE
install service dependencies from fuge shell

### ISSUE THREAD

**Issue by davidmarkclements** [apparatus/fuge#26]
if I clone a project with a bunch of services it's a drag to cd into seach service and npm install, 
so

```
fuge > setup <service>
```
```
fuge > setup all
```

I'm thinking setup here, instead of install because "fuge install service" sounds like we're installing the service, instead of install the existing services dependencies. another option is `fuge> install-deps-of service` but it .. `setup service` is catchier

**Comment by pelger** [comment]
There is already a fuge build command - this extracts the RUN entries out of each Dockerfile and creates a build script. Can also be overridden in fuge-config. Is this what you mean?

**Comment by davidmarkclements** [comment]
I was focused on *just* doing the the npm install, but I suppose fuge build does

**Comment by pelger** [comment]
Cool and the gang
