### ISSUE TITLE
should we have a community repo?

### ISSUE THREAD

**Issue by davidmarkclements** [apparatus/fuge#3]
* centralise all issues for all repos
* repo list
* maintain contributor list
* licenses
* contributor guide
* etc. etc.

examples: 
https://github.com/Level/community  (for community pieces)
https://github.com/nearform/deck  (for centralising issues)

**Comment by mcollina** [comment]
Not sure. I think we want to build other stuff other than fuge, so we'll have multiple things.

**Comment by mcdonnelldean** [comment]
We already do for the org: https://github.com/apparatus/contrib

**Comment by AdrianRossouw** [comment]
@davidmarkclements so this can be closed?

**Comment by davidmarkclements** [comment]
yah closing - tx @AdrianRossouw
