### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by alessioalex** [apparatus/fuge#32]
"fuge" in Romanian literally means "is running" (as in "he is running around the park", not "the process is running").

Thought you may find this funny enough to include in the readme.

Cheers.

**Comment by AdrianRossouw** [comment]
that's actually pretty great. I wonder if it has latin roots?

Here at nearform we have 2 open source 'brands' we are building..

1. there's the devops stuff which is being built under apparatus, generally named around lab equipment.
1. there's our microservices stuff under seneca, which is all latin names.

I like the symbolism of having certain names that fit into both categories.

**Comment by marcopiraccini** [comment]
In latin "fugere" is "to flee", so it's different. 
"fuge" in latin is imperative, it's literally "Flee!". Not sure it's good to write that on the readme :)

**Comment by alessioalex** [comment]
@AdrianRossouw @marcopiraccini you guys are on to something, I think it does come from latin: https://ro.wiktionary.org/wiki/fugi

"Fugi!" is an imperative for "Run away!", "a fugi" (the verb) means "to run", "fuge" means "(he/she) is running".

**Comment by pelger** [comment]
Thats awesome :) the name originally came from a contraction of "centrifuge" being a piece of equipment in a micro-biological lab.. micro-services etc... fairly weak I know but I think that the whole flee / runaway thing makes sense - i.e. runaway from big ugly platforms... :)

**Comment by AdrianRossouw** [comment]
I think this is interesting, but not particularly actionable until we settle on branding, and might be more appropriate on the website somewhere.

thanks for bringing it to our attention @alessioalex.
