### ISSUE TITLE
debug command crashes fuge

### ISSUE THREAD

**Issue by matthewoconnor-development** [apparatus/fuge#35]
It looks like in the fuge-runner system.js file the start function arguments within the debug function are incorrect. It is only passing in system, name and cb but start requires a count argument also. This is making the cb become assigned to the count variable in start and crashing the program. I have done a fix locally that works just fine, can PR the affected repos if you like?

**Comment by matthewoconnor-development** [comment]
Issue was in fuge-runner, a PR fix has been made.

**Comment by pelger** [comment]
Thanks!! The debug command is experimental will be replaced shortly but appreciate the fix!
