### ISSUE TITLE
Allow for running services in containers as well

### ISSUE THREAD

**Issue by bsander** [apparatus/fuge#41]
Fuge chooses to start all services as processes instead of containers. It would be great to have an option to start services in their containers as well, while of course maintaining as many of the fuge shell features as possible (like watching for changes and log grepping). This would help in dealing with services that rely for example on different versions of node, or maybe even include services that have been written in other languages as well.

**Comment by AdrianRossouw** [comment]
we use the docker-compose format, so you can just use docker-compose up to run the services.

**Comment by bsander** [comment]
Yes, but I can't use `fuge shell` in that situation, can I?

**Comment by AdrianRossouw** [comment]
so actually this does work, and it will pick up services in your docker-compose file that are being run from an image and not a path. At the moment it isn't smart enough to pull the images for those containers itself though (see: #48)

**Comment by bsander** [comment]
I'm not talking about things like redis or elasticsearch, but about the microservices I'm actually developing on top of that. Basically I'm just looking for a way to run `docker-compose up`, and then be able to manage the resulting ecosystem, like `fuge shell` does (starting/stopping individual microservices, rebuilding on file changes, etc). I don't really want *anything* to be running as a local process if it can be run in a docker container instead. Is such a setup possible with fuge?

**Comment by grandmore** [comment]
@bsander Did you find an answer? 

I am having issue trying to get `docker-compose up` to work with fuge. I assume that I should be able to launch and connect each of the components automatically using compose.

Thanks.

**Comment by bsander** [comment]
Unfortunately I didn't, I'd still be interested though :)

**Comment by mcdonnelldean** [comment]
@bsander I see what you are saying. Generally, no, fuge won't every get the ability to auto generate and run your containers like that. We tried this with a previous version of fuge and with was hacky at best. 

For the short term Fuge won't be able to generate and run containers but we are looking at adding plugin ability so that it's something you can write yourself. 

I'm going to go ahead and close as answered but feel free to reopen if you have anymore questions.
