### ISSUE TITLE
broken for me in starting docker containers

### ISSUE THREAD

**Issue by mcollina** [apparatus/fuge#50]
? fuge> [influx - 73237]: An error occurred trying to connect: Post https://192.168.59.103:2375/v1.20/containers/create: dial tcp 192.168.59.103:2375: i/o timeout
process exit [73237]: influx

currently $DOCKER_HOST is set at tcp://192.168.99.100:2376

docker is v1.8.1
node is v4.2.4

It seems that fuge is trying to connect to 192.168.59.103 rather than 192.168.99.100.

**Comment by mcollina** [comment]
I'm not sure what's happening and how I debug this.

**Comment by AdrianRossouw** [comment]
@mcollina this was due to you having old boot2docker details in your bashrc, right ?

what do you think needs to happen to resolve this?

**Comment by mcollina** [comment]
So, `fuge-runner` includes the .bashrc when executing commands (this may cause additional side effects). I think we should not do that, as it might change the node environment (because of nvm).

I had an old DOCKER_HOST definition in my bashrc.

**Comment by AdrianRossouw** [comment]
there's a fix for this here : https://github.com/apparatus/fuge-runner/pull/5

**Comment by AdrianRossouw** [comment]
merged
