### ISSUE TITLE
tab-completion of service names

### ISSUE THREAD

**Issue by mcollina** [apparatus/fuge#52]
It would be awesome if we could auto-complete the service names in the shell when using `start`, `stop`, etc..

**Comment by mcdonnelldean** [comment]
For the love of all... YES!!!! Also exit <proc> should alias stop so I don't kill my system by mistake!

**Comment by AdrianRossouw** [comment]
@matt-oc you added the auto-completion support... do you have any inpiut on how to add this via vorpal?

@mcdonnelldean exit and quit are already aliased. stop is something different.

**Comment by mcdonnelldean** [comment]
@AdrianRossouw Maybe it's not released yet? I'll make an issue on the other thing.

**Comment by matt-oc** [comment]
@mcollina @AdrianRossouw @mcdonnelldean I have this working now, will PR tomorrow after some tidying, its very handy :smile:
