### ISSUE TITLE
fuge-config override example

### ISSUE THREAD

**Issue by feugy** [apparatus/fuge#55]
In the `fuge-config.js` file, I'd like to activate watch on all services, except one.
I'v tried this:
```javascript
module.exports = {
  runDocker: false,
  proxy: 'all',
  tail: true,
  monitor: true,
  exclude: /node_modules|\.git|\.log/mgi,
  overrides: {
    fast_ui: {
      monitor: false
    }
  }
};
```
(`fast_ui` is my service's name, not the folder itself which is different)

But when starting fuge shell, a `ps` command show that the service is still watch.
Can you provide a short working overriding example ?

**Comment by mcdonnelldean** [comment]
@feugy I know @AdrianRossouw Is doing a bunch of stuff on this currently so when we get a example of the new overrides I will post em here.

**Comment by mcdonnelldean** [comment]
See https://github.com/nodezoo/nodezoo-system for an example system using overrides.

**Comment by danielo515** [comment]
What the ? Is fuge supporting javascript files as config ?
