### ISSUE TITLE
proxy shouldn't run on linux

### ISSUE THREAD

**Issue by AdrianRossouw** [apparatus/fuge#56]
Just had a support request where the user was unable to run a docker container for postgres in fuge on an ubuntu os, because of this error message:

```
fuge shell system.yml 
compiling...
starting proxy...
  proxy postgres 5432 -> 192.168.1.6:5432
  proxy mesh 10000 -> 192.168.1.6:20000
  proxy concorda 10001 -> 192.168.1.6:20001
  proxy dashboard 10002 -> 192.168.1.6:20002
  proxy client 10003 -> 192.168.1.6:20003
starting shell..
? fuge> start postgres
running: postgres
? fuge> [postgres - 16162]: Error response from daemon: Cannot start container f2ef544bd8ff9e03af7b2fc74d1cae59365b68012cf87c181abd1951cfdf4a6d: failed to create endpoint gigantic_fermat on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
process exit [16162]: postgres
```

What it eventually ended up being was that the proxy was running on his ubuntu machine, trying to forward localhost:5432 to localhost:5432, and therefor brought down the process.

When he changed the `{proxy: 'all'}` in his fuge-config, it stopped happening.

we need to be detecting whether the proxy needs to run, instead of requiring users on different operating systems to change their config files (that doesn't scale).

**Comment by pelger** [comment]
Closing as proxy now removed as not required with Docker for mac/windows
