### ISSUE TITLE
Exit <service> kills all services

### ISSUE THREAD

**Issue by mcdonnelldean** [apparatus/fuge#57]
I am in the habit of typing exit <service> over stop <service> by accident. One thing I noticed is exit process will exit the whole system (as I assume it ignores the input). Can we have it so that exit <service> does nothing or just stops a process. I'm going to go out on a limb and say if someone types exit <service> they are not looking to exit the whole system.

**Comment by mcdonnelldean** [comment]
@AdrianRossouw @davidmarkclements So on this, can we have it even say, like git or npm, 

`did you mean stop <xyz>` I fully appreciate this is a fat finger user mistake but I do think the measure of a tools friendliness is in features like this.

**Comment by mcdonnelldean** [comment]
This could also be another for @matt-oc

**Comment by davidmarkclements** [comment]
Totally in agreement on best ux (which also just prompted me to make #69)

**Comment by timoweiss** [comment]
In the current version, typing `exit` results in keeping the started processes running right?

**Comment by matt-oc** [comment]
Addressed in #80
