### ISSUE TITLE
dokku deployment

### ISSUE THREAD

**Issue by khwerhahn** [apparatus/fuge#59]
Hi,

has anyone tried fuge with [dokku](https://github.com/dokku/dokku)? It would be awesome if they work together. I use dokku extensively for all sorts of projects, but only for monolithic apps so far. Makes the deployment very easy.

I'm new to the whole microservice and docker thing and not exactly sure how I would set up a good development/deployment process.

**Comment by mcdonnelldean** [comment]
@khwerhahn The idea is for Fuge to play nice with as many upstreams as possible. I know @mcollina is working on one called Oast. Generally the big blocker to this would be a body to do it. Is this something you would be interested in looking at?

Overall though the purpose of all the tools in the Apparatus org is to play nice as part of larger processes but we are early days yet.

**Comment by khwerhahn** [comment]
I would love to help, but I'm tightly caught up in a project currently. Once I'll find the time, I'll get back to you.

**Comment by mcdonnelldean** [comment]
Sounds epic!
