### ISSUE TITLE
Service names in serviceTest.js don't match names in service.js when generating service.

### ISSUE THREAD

**Issue by taji** [apparatus/fuge#60]
I'm running this:

    fuge generate service
    Service name (servicelvj9s0): blah
    create package.json
    create service.js
    create README.md
    create test/serviceTest.js
    create Dockerfile
    create .jshintrc
    create .istanbul.yml
    create .gitignore

The files are generated as expected.  In service.js we have:

![2016-03-13 07_36_56-digital-ocean-dev - cloud9](https://cloud.githubusercontent.com/assets/702031/13728743/e9e4e720-e8ef-11e5-877f-7999a6097a21.png)

However, in tests/serviceTests.js we have: 

![2016-03-13 07_41_12-digital-ocean-dev - cloud9](https://cloud.githubusercontent.com/assets/702031/13728770/7b54d9a4-e8f0-11e5-8695-d19586f60c53.png)

Looking at the code (and assuming I'm not missing your intent), the problem is in generator-fuge in your serviceTest.js template:

![image](https://cloud.githubusercontent.com/assets/702031/13728808/d386f458-e8f1-11e5-93c8-f03467e1f716.png)

I've sent you a pull request. Note I made the fix in github directly, so it hasn't been tested. Please let me know if additional steps are necessary.

**Comment by mcdonnelldean** [comment]
Good spot! Someone should be able to look over it soon. I don't see a pull request though, has it been looked after already?

**Comment by taji** [comment]
Not yet. :).  Here is the pull request:

https://github.com/apparatus/generator-fuge/pull/5

**Comment by shanel262** [comment]
@davidmarkclements @mcdonnelldean Can be closed?

**Comment by mihaidma** [comment]
@shanel262 the generator functionality is removed from fuge. I think this can be closed

**Comment by mcdonnelldean** [comment]
Yup can be closed

Kindest Regards,

Dean

On 26 Jul 2016, at 18:29, Mihai Dima <notifications@github.com<mailto:notifications@github.com>> wrote:


@shanel262<https://github.com/shanel262> the generator functionality is removed from fuge. I think this can be closed

-
