### ISSUE TITLE
Cannot delete service name if mistake is made while typing.

### ISSUE THREAD

**Issue by fourq** [apparatus/fuge#61]
Cannot delete service name if mistake is made while typing.

```sh
node:v4.4.0 npm:v3.8.1 ∑ forms/
ø fuge generate service
? Service name (service001fo): <HERE>
```

OS X El Capitan 10.11.3
iTerm2 2.9.20160206

**Comment by mcdonnelldean** [comment]
@fourq The service name just ends up in the yaml files, from there you are free to change it to whatever you like. Or am I missing something here?

**Comment by pelger** [comment]
To be clear, the service name can be changed at any time by editing the yaml file. Also the build path can be changed in the yaml file and the service directory renamed. Going to close this issue. @fourq please do re-open if we have mis-understood. Thanks!

**Comment by fourq** [comment]
What I mean is, as you start typing the service name in the term at `? Service name (service001fo): ` if you push backspace to change the name when you make a mistake, you cannot. You have to ctrl+c out of it and start over. Sorry for the vague post.
