### ISSUE TITLE
Allow for a start and stop of multiple processes in one command (but not all)

### ISSUE THREAD

**Issue by Georgette** [apparatus/fuge#66]
the current set of commands allow for this:

```
start all
stop all
```

or 

```
start service1
start service2
start service3

stop service1
stop service2
stop service3

```

It would be convenient to allow for something like this in the CLI:

```
start service1 service2 service3
stop service1 service2 service3
```

**Comment by mcdonnelldean** [comment]
@davidmarkclements Is this a big job? Is this something we could get @matt-oc to take a swing at?

**Comment by davidmarkclements** [comment]
@mcdonnelldean not super big

parse the command, create an array of services, loop through array and call the function for a single service for each

the difficult part will be grokking where these pieces are

how about @matt-oc gives it a whirl, and if he needs any additional context he can always get in touch with myself, @geek, @AdrianRossouw or @pelger ?

**Comment by dottorblaster** [comment]
A rough way to do this would be in the fuge shell. Anyway, I was thinking about an alternative approach: make the fuge shell only a middleware, and create a dedicated function in the fuge-runner that runs "only some" services, maybe refactoring startAll and stopAll externalizing the async stuff in a separate block.

I was starting to give it a shot on Friday but then my girlfriend kidnapped me for this Easter weekend.

**Comment by mcdonnelldean** [comment]
Awesome stuff, spoke to @matt-oc he is going to give this a shot once he finishes up on some other work he's doing.

**Comment by matt-oc** [comment]
Adressed in #80
