### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by davidmarkclements** [apparatus/fuge#7]
1. prompt-sync does fs.openSync('/dev/stdin', 'rs')  - preliminary research suggests there is no  /dev/stdin equivalent on windows (hopefully there's something..)
2. on occasion we're concatenating paths instead of path.join

**Comment by mcdonnelldean** [comment]
@davidmarkclements There might also be some issues that are Seneca / Windows specific. If you find them pop em on the Seneca board. This is something @rjrodger is interested in improving so we can get people on it.

**Comment by jondlm** [comment]
I've had a lot of issues getting sync prompting to work correctly with my node cli tools. I finally broke down and started using a promise chain which allowed me to use [inquirer](https://www.npmjs.com/package/inquirer). That library has all the bells and whistles. Not sure about their windows support but I'd be willing to bet it's good.

**Comment by davidmarkclements** [comment]
hey thanks @jondlm - yah we're using yeoman under the hood too which actually uses inquirer - 
I love the idea of a synchronous prompt for code simplicity - promises are certainly an option but something I've been considering is using a conditionally installed native module fallback for windows (and possibly node .10). Since prompt-sync is wrapped in https://github.com/davidmarkclements/incite and positive it would be straight forward to update these modules and have a fix without any refactoring in fuge code base

**Comment by davidmarkclements** [comment]
ok I've discovered a prompt-sync fix for both windows and node 0.10 

https://github.com/0xxff/prompt-sync/pull/9

Nevertheless, I'm going to create a reduced features version of `prompt-sync` for the `incite` and `positive` modules so we're not waiting on the PR. 

thanks @jondlm for inspiring me to investigate

**Comment by davidmarkclements** [comment]
ok so the prompt issue for windows is solved - 

but we still need to investigate seneca issues and any others that may arise - pending investigation

https://github.com/apparatus/fuge/commit/eb04270c5aed8064c37a59a817b032207ac741c9

https://github.com/davidmarkclements/syncoprompt

https://github.com/davidmarkclements/incite/commit/00e3ebbef86bc995d26666afddf5ad1cf78fa871

https://github.com/davidmarkclements/positive/commit/41559d92aba4641f7f061e6d5d4c3ec242f1f5c7

**Comment by pelger** [comment]
Awesome stuff!

**Comment by davidmarkclements** [comment]
@pelger didn't you close out the final pieces of this this last week  - okay to close issue?

**Comment by pelger** [comment]
@davidmarkclements just wrapping this up today - will have a PR shortly

**Comment by pelger** [comment]
I believe that windows support should be sorted now - can one of you guys please install the latest version for me and double check. Cheers.

**Comment by JeffryGonzalez** [comment]
Running on Win 10 - was having problems with watch, but seems to be working great now. Thanks!

**Comment by pelger** [comment]
Awesome - thanks for checking - will close this now.
