### ISSUE TITLE
unable to stop and start a process again

### ISSUE THREAD

**Issue by timoweiss** [apparatus/fuge#75]
Steps to reproduce:
* `fuge generate system`
* `fuge shell  fuge/docker-compose.yml`
* `fuge start`
* `fuge stop`
* `fuge start` -> nothing is happening

**Comment by timoweiss** [comment]
As far as I can tell, it is because the type of the service will be changed from `process` to `node`. In the start command is a check `(container.type === 'process' || container.type === 'docker') && container.specific.execute` which will be false. This prevents the processRunner to start again.

See: https://github.com/apparatus/fuge-runner/blob/master/lib/system.js#L132

**Comment by mcdonnelldean** [comment]
To add to this, I run a system of 'non generated' services and can start and stop fine. May or may not be of value when testing.

**Comment by AdrianRossouw** [comment]
i ran into this now. will check it out.

**Comment by geek** [comment]
@timoweiss thanks for the details, I added a PR to fix this

**Comment by timoweiss** [comment]
cool :) you guys doing a great job!! :dancer:

**Comment by timoweiss** [comment]
@geek with the PR it works as expected. Thanks :)

**Comment by AdrianRossouw** [comment]
just release 0.6.3 with the fix included.
