### ISSUE TITLE
Fuge commands are case sensitive

### ISSUE THREAD

**Issue by CodeWriterWriter** [apparatus/fuge#76]
Entering "EXIT" prompts this response:
? fuge> EXIT

  Commands:

    exit   Exits application.
Instead of exiting the shell.
Commands should be case insensitive

**Comment by AdrianRossouw** [comment]
@matt-oc since you added the vorpal stuff, maybe this is in your wheelhouse?

**Comment by matt-oc** [comment]
@AdrianRossouw I'll have a look see :+1:

**Comment by mihaidma** [comment]
I suppose commands are expected to be case sensitive like in most tools.
Moreover it is nice that it displays a hint close to the command entered.

I'll close. Please reopen if you think otherwise.
