### ISSUE TITLE
Seneca: gate-executor: listen EADDRINUSE 0.0.0.0:20000

### ISSUE THREAD

**Issue by grandmore** [apparatus/fuge#83]
I am getting an address clash the second time I start the example code. The first time it worked.

I am using version huge 0.6.4, because of the problem with simple-grep@0.0.2 not being available at present.

If I run `fuge generate system` and use the 'hapi' defaults, everything installs as expected.
I can then enter the shell with `fuge shell` and run `ps` to see the running processes. I get the shell output
    proxy frontend 10000 -> 192.168.1.6:20000
    proxy api 10001 -> 192.168.1.6:20001
    proxy service1 10002 -> 192.168.1.6:20002
    proxy service2 10003 -> 192.168.1.6:20003

I then run `ps` to see the running processes and they are all "off".
I then run `start` and the services start to launch then some stop with the error

    Seneca Fatal Error
    ==================
    
    Message: seneca: gate-executor: listen EADDRINUSE 0.0.0.0:20000

I have checked my processes and there is nothing using this address. Also initially when I was checking services2 did not work but now services2 and service1 both complain of the same thing.

I am also using node 5.11.0 the latest stable version.

**Comment by grandmore** [comment]
After writing this I went back and continued testing and found the issue.

Instead of using the command `fuge shell ./fuge/compose-dev.yml` I can enter the folder and run the command `fuge shell`. Everything behaves as normal apart from the problem I have hilighted. Using the shortcut path causes the problem.

I hope this helps.

Nice platform so far.

**Comment by mcdonnelldean** [comment]
Hey @grandmore I couldn't reproduce on the latest releases of fuge and Seneca. If you come across this in later versions please let us know, cheers.

**Comment by jacobbubu** [comment]
I've encountered the same problem with fuge v0.7.0. There is a bunch of processes left after running start in fuge shell (exited fuge):
<img width="841" alt="fuge1" src="https://cloud.githubusercontent.com/assets/1164378/17021621/bdd1b274-4f7b-11e6-8aa6-526ff3cdcc80.png">

I've to kill then all before re-run these services in fuge shell:
```
kill $(ps -A | grep /fuge/fuge.js | awk '{print $1}')
```
