### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by jmatsushita** [apparatus/fuge#87]
It seems there used to be a debug command #35 but no more.

to help me troubleshoot #86 it would be quite helpful to know what fuge is doing behind the scenes when using for instance a `--debug` flag.

**Comment by jmatsushita** [comment]
Ah it seems that the debug command is in the shell. I'm talking about the `fuge` CLI.

**Comment by lucamaraschi** [comment]
@jmatsushita I found the debug command available in the `fuge CLI`, is that also for you?

**Comment by mcdonnelldean** [comment]
Debug should be in the CLI. If it is still not the case for you @jmatsushita could you log your OS, Node version, NPM version and of course Fuge version? I'll close for now but please reopen if needed.
