### ISSUE TITLE
Is Windows support planned?

### ISSUE THREAD

**Issue by StarpTech** [apparatus/fuge#96]
https://github.com/apparatus/fuge/issues/95
https://github.com/apparatus/xeno-compose/issues/7

**Comment by mcdonnelldean** [comment]
@StarpTech Yes, it is something that is being investigated along with tooling to ensure it stays compatible.

**Comment by BhaskaranR** [comment]
all of of our offshore team members use windows, can we fix spacing issues with priority?

**Comment by lucamaraschi** [comment]
@BhaskaranR do you mean #95?

**Comment by BhaskaranR** [comment]
yes and also issue #79

**Comment by mcdonnelldean** [comment]
Yes, there is being work done over the next to weeks to enable.

**Comment by mcdonnelldean** [comment]
Merged with #99
